import type {
  AchievementId,
  CardDefinition,
  EnemyDefinition,
  FloorDefinition,
  ItemDefinition,
  ProfileState,
} from './types.js';
import { ACHIEVEMENT_DEFINITIONS } from './achievements/catalog.js';
import { isFamiliarItem } from './combat/familiars.js';
import { CUSTOM_ITEM_DEFINITIONS } from './content/custom-items.js';
import { FULL_ISAAC_ITEMS } from './content/isaac-items.generated.js';
import {
  CURRENT_ITEM_UNLOCK_PROGRESSION_VERSION,
  buildItemUnlockProgression,
} from './progression/item-unlocks.js';
import {
  AttackMode,
  CardEffectOpcode,
  CardTarget,
  CardType,
  EnemyMovementPattern,
  HEART_SIZE_UPGRADE_AMOUNT,
  ItemKind,
  ItemUseTiming,
  RewardPool,
  RewardQuality,
  StatusKind,
  TREATMENT_BASE_HEAL,
  UnlockEvent,
} from './types.js';

export const FLOORS: FloorDefinition[] = [
  {
    index: 0,
    name: 'Basement I',
    subtitle: 'Something stirs below',
    bossName: 'Monstro',
    palette: '#75584a',
  },
  {
    index: 1,
    name: 'Basement II',
    subtitle: 'The walls begin to breathe',
    bossName: 'Duke of Flies',
    palette: '#67483f',
  },
  { index: 2, name: 'Caves I', subtitle: 'Cold stone, hungry dark', bossName: 'Gurdy', palette: '#4d625b' },
  { index: 3, name: 'Caves II', subtitle: 'No way but down', bossName: 'Mega Fatty', palette: '#40564f' },
  { index: 4, name: 'Depths I', subtitle: 'A familiar voice', bossName: 'The Cage', palette: '#5b4a5e' },
  { index: 5, name: 'Depths II', subtitle: 'Mother is watching', bossName: "Mom's Leg", palette: '#693e50' },
];

export const CARDS: Record<string, CardDefinition> = {
  'basic-attack': {
    id: 'basic-attack',
    name: 'Attack',
    type: CardType.Attack,
    cost: 1,
    value: 6,
    description: 'Perform one basic attack with the current attack form. Item cards can be fused into it.',
    target: CardTarget.Enemy,
    icon: '●',
    quality: RewardQuality.Common,
    rewardPools: [RewardPool.RoomClear],
  },
  'double-shot': {
    id: 'double-shot',
    name: 'Double Shot',
    type: CardType.Attack,
    cost: 2,
    value: 4.2,
    hits: 2,
    description: 'Deal 70% attack damage twice.',
    target: CardTarget.Enemy,
    icon: '●●',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.RoomClear, RewardPool.Treasure, RewardPool.Shop, RewardPool.Challenge],
    rewardWeight: 9,
  },
  'sweeping-attack': {
    id: 'sweeping-attack',
    name: 'Sweeping Attack',
    type: CardType.Attack,
    cost: 2,
    value: 3.9,
    description: 'Deal 65% attack damage to every enemy.',
    target: CardTarget.AllEnemies,
    icon: '◉',
    quality: RewardQuality.Rare,
    rewardPools: [RewardPool.RoomClear, RewardPool.Challenge, RewardPool.Vault],
    rewardWeight: 5,
  },
  'wooden-cross': {
    id: 'wooden-cross',
    name: 'Wooden Cross',
    type: CardType.Shield,
    cost: 1,
    value: 5,
    description: 'Gain 5 shield. Unplayable at the current shield limit.',
    target: CardTarget.Self,
    icon: '✚',
    quality: RewardQuality.Common,
    rewardPools: [RewardPool.RoomClear, RewardPool.Shop, RewardPool.Angel, RewardPool.Bedroom],
    rewardWeight: 14,
  },
  'half-heart': {
    id: 'half-heart',
    name: 'Treatment',
    type: CardType.Recovery,
    cost: 1,
    value: TREATMENT_BASE_HEAL,
    description: 'Recover 10 red-heart HP. Upgrades add 3 HP. Unplayable at full red-heart HP.',
    target: CardTarget.Self,
    icon: '♥',
    quality: RewardQuality.Common,
    rewardPools: [RewardPool.RoomClear, RewardPool.Shop, RewardPool.Bedroom, RewardPool.Arcade],
    rewardWeight: 12,
  },
  'vitality-shot': {
    id: 'vitality-shot',
    name: 'Vitality Shot',
    type: CardType.Vitality,
    cost: 0,
    value: 2,
    description: 'Gain 2 vitality this turn. Upgrades grant 3. Exhaust permanently after use.',
    target: CardTarget.Self,
    exhaust: true,
    icon: 'ϟ',
    quality: RewardQuality.Common,
    rewardPools: [RewardPool.RoomClear],
    rewardWeight: 5,
  },
  'bad-trip': {
    id: 'bad-trip',
    name: 'Bad Trip',
    type: CardType.Hex,
    cost: 2,
    value: 2,
    description:
      'Curse an enemy for 2 turns. Its attacks deal 40% less and its special bundles are suppressed.',
    target: CardTarget.Enemy,
    icon: '☠',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.RoomClear, RewardPool.Curse, RewardPool.Devil],
    rewardWeight: 5,
  },
  'the-empress': {
    id: 'the-empress',
    name: 'III · The Empress',
    type: CardType.Tarot,
    cost: 2,
    value: 2,
    description: 'Gain +2 damage for this combat. Exhaust permanently.',
    target: CardTarget.Self,
    exhaust: true,
    icon: 'Ⅲ',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.RoomClear, RewardPool.Sacrifice, RewardPool.Arcade, RewardPool.Vault],
    rewardWeight: 3,
  },
  death: {
    id: 'death',
    name: 'XIII · Death',
    type: CardType.Tarot,
    cost: 3,
    value: 18,
    description: 'Deal 18 damage to every enemy. Exhaust permanently.',
    target: CardTarget.AllEnemies,
    exhaust: true,
    icon: 'ⅩⅢ',
    quality: RewardQuality.Rare,
    rewardPools: [
      RewardPool.Challenge,
      RewardPool.Curse,
      RewardPool.Devil,
      RewardPool.Sacrifice,
      RewardPool.Vault,
    ],
    rewardWeight: 2,
  },
  'the-sun': {
    id: 'the-sun',
    name: 'XIX · The Sun',
    type: CardType.Tarot,
    cost: 4,
    value: 18,
    description: 'Deal 18 to all enemies and recover 10 HP. Exhaust permanently.',
    target: CardTarget.AllEnemies,
    exhaust: true,
    icon: '☀',
    quality: RewardQuality.Legendary,
    rewardPools: [
      RewardPool.Angel,
      RewardPool.SuperSecret,
      RewardPool.Sacrifice,
      RewardPool.Vault,
      RewardPool.Error,
    ],
    rewardWeight: 1,
  },
  'dead-weight': {
    id: 'dead-weight',
    name: 'Dead Weight',
    type: CardType.Curse,
    cost: 99,
    description: 'Unplayable. Created by enemy curses.',
    target: CardTarget.None,
    icon: '▧',
    quality: RewardQuality.Common,
    rewardPools: [RewardPool.Curse],
  },
  blank: {
    id: 'blank',
    name: 'Blank',
    type: CardType.Blank,
    cost: 99,
    description: 'No effect. Deck-editing and Blank Book effects can turn this empty slot into value.',
    target: CardTarget.None,
    icon: '□',
    quality: RewardQuality.Poor,
    rewardPools: [],
  },
  silence: {
    id: 'silence',
    name: 'Silence',
    type: CardType.Hex,
    cost: 2,
    description: 'Silence an enemy for 2 turns. It cannot execute attack actions.',
    target: CardTarget.Enemy,
    icon: '⌁',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.Curse, RewardPool.Devil, RewardPool.Library],
    rewardWeight: 4,
    effects: [
      {
        opcode: CardEffectOpcode.ApplyStatus,
        status: StatusKind.Silence,
        turns: 2,
        target: CardTarget.Enemy,
      },
    ],
  },
  poison: {
    id: 'poison',
    name: 'Poison',
    type: CardType.Hex,
    cost: 1,
    description: 'Poison an enemy for 3 turns. It loses 4 HP before acting each turn.',
    target: CardTarget.Enemy,
    icon: '☣',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.Curse, RewardPool.Devil, RewardPool.Secret],
    rewardWeight: 6,
    effects: [
      {
        opcode: CardEffectOpcode.ApplyStatus,
        status: StatusKind.Poison,
        turns: 3,
        amount: 4,
        target: CardTarget.Enemy,
      },
    ],
  },
  blind: {
    id: 'blind',
    name: 'Blind',
    type: CardType.Hex,
    cost: 1,
    description: 'Blind an enemy for 2 turns. Its next intent is replaced by random actions.',
    target: CardTarget.Enemy,
    icon: '◑',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.Curse, RewardPool.Secret, RewardPool.Library],
    rewardWeight: 5,
    effects: [
      {
        opcode: CardEffectOpcode.ApplyStatus,
        status: StatusKind.Blind,
        turns: 2,
        target: CardTarget.Enemy,
      },
    ],
  },
  'armor-break': {
    id: 'armor-break',
    name: 'Armor Break',
    type: CardType.Hex,
    cost: 1,
    description: 'Break an enemy’s armor for 2 turns. All incoming damage ignores armor.',
    target: CardTarget.Enemy,
    icon: '◇',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.RoomClear, RewardPool.Challenge, RewardPool.Elite],
    rewardWeight: 5,
    effects: [
      {
        opcode: CardEffectOpcode.ApplyStatus,
        status: StatusKind.ArmorBreak,
        turns: 2,
        target: CardTarget.Enemy,
      },
    ],
  },
  weak: {
    id: 'weak',
    name: 'Weak',
    type: CardType.Hex,
    cost: 1,
    description: 'Weaken an enemy for 2 turns. Its attacks deal 50% less damage.',
    target: CardTarget.Enemy,
    icon: '▽',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.RoomClear, RewardPool.Curse, RewardPool.Angel],
    rewardWeight: 5,
    effects: [
      {
        opcode: CardEffectOpcode.ApplyStatus,
        status: StatusKind.Weak,
        turns: 2,
        target: CardTarget.Enemy,
      },
    ],
  },
  'item-lock': {
    id: 'item-lock',
    name: 'Item Lock',
    type: CardType.Hex,
    cost: 2,
    description: 'Seal an enemy’s special actions for 2 turns; it may only move or make basic attacks.',
    target: CardTarget.Enemy,
    icon: '⊘',
    quality: RewardQuality.Rare,
    rewardPools: [RewardPool.Curse, RewardPool.Devil, RewardPool.Challenge],
    rewardWeight: 3,
    effects: [
      {
        opcode: CardEffectOpcode.ApplyStatus,
        status: StatusKind.ItemLock,
        turns: 2,
        target: CardTarget.Enemy,
      },
    ],
  },
  'skill-d6': {
    id: 'skill-d6',
    name: 'The D6',
    type: CardType.Skill,
    cost: 3,
    description: 'Exchange every other Item card in hand with random cards from the draw and discard piles.',
    target: CardTarget.None,
    icon: '⚅',
    quality: RewardQuality.Legendary,
    rewardPools: [RewardPool.Treasure, RewardPool.Dice, RewardPool.Error],
  },
  'skill-yum-heart': {
    id: 'skill-yum-heart',
    name: 'Yum Heart',
    type: CardType.Skill,
    cost: 2,
    description: 'Recover 15 red-heart HP.',
    target: CardTarget.Self,
    icon: '♥',
    quality: RewardQuality.Uncommon,
    rewardPools: [RewardPool.Treasure, RewardPool.Shop, RewardPool.Bedroom, RewardPool.Arcade],
  },
  'skill-belial': {
    id: 'skill-belial',
    name: 'Book of Belial',
    type: CardType.Skill,
    cost: 2,
    description: 'Gain +1 damage for this room.',
    target: CardTarget.Self,
    icon: '✦',
    quality: RewardQuality.Rare,
    rewardPools: [RewardPool.Devil, RewardPool.Treasure, RewardPool.Library, RewardPool.Curse],
  },
  'skill-shadows': {
    id: 'skill-shadows',
    name: 'Book of Shadows',
    type: CardType.Skill,
    cost: 2,
    description: 'Gain 12 shield.',
    target: CardTarget.Self,
    icon: '◈',
    quality: RewardQuality.Rare,
    rewardPools: [RewardPool.Treasure, RewardPool.Angel, RewardPool.Library],
  },
  'skill-tammy': {
    id: 'skill-tammy',
    name: "Tammy's Head",
    type: CardType.Skill,
    cost: 2,
    description: 'Deal attack damage to all enemies.',
    target: CardTarget.AllEnemies,
    icon: '✺',
    quality: RewardQuality.Uncommon,
    rewardPools: [
      RewardPool.Treasure,
      RewardPool.Secret,
      RewardPool.SuperSecret,
      RewardPool.Library,
      RewardPool.Crawlspace,
    ],
  },
  'skill-nail': {
    id: 'skill-nail',
    name: 'The Nail',
    type: CardType.Skill,
    cost: 3,
    description: 'Gain a black heart and +1 armor this room.',
    target: CardTarget.Self,
    icon: '†',
    quality: RewardQuality.Rare,
    rewardPools: [RewardPool.Devil, RewardPool.Curse, RewardPool.Sacrifice],
  },
  'skill-hourglass': {
    id: 'skill-hourglass',
    name: 'Glowing Hour Glass',
    type: CardType.Skill,
    cost: 3,
    description: 'All enemies lose their next action.',
    target: CardTarget.AllEnemies,
    icon: '⌛',
    quality: RewardQuality.Rare,
    rewardPools: [RewardPool.Shop, RewardPool.Planetarium, RewardPool.Dice, RewardPool.Vault],
  },
};

const CURATED_ITEMS: Record<string, ItemDefinition> = {
  d6: {
    id: 'd6',
    isaacId: 105,
    name: 'The D6',
    kind: ItemKind.Active,
    pool: [RewardPool.Treasure, RewardPool.Dice, RewardPool.Error, RewardPool.Library],
    quality: RewardQuality.Legendary,
    icon: '⚅',
    chargeRounds: 3,
    skillCardId: 'skill-d6',
    description:
      'Exchanges every other Item card in hand with random cards from the draw and discard piles. Isaac starts with it.',
  },
  'yum-heart': {
    id: 'yum-heart',
    isaacId: 45,
    name: 'Yum Heart',
    kind: ItemKind.Active,
    pool: [RewardPool.Treasure, RewardPool.Shop, RewardPool.Bedroom, RewardPool.Arcade],
    quality: RewardQuality.Uncommon,
    icon: '♥',
    chargeRounds: 4,
    skillCardId: 'skill-yum-heart',
    description: 'Recovers 15 red-heart HP.',
  },
  'book-belial': {
    id: 'book-belial',
    isaacId: 34,
    name: 'Book of Belial',
    kind: ItemKind.Active,
    pool: [RewardPool.Devil, RewardPool.Treasure, RewardPool.Library, RewardPool.Curse],
    quality: RewardQuality.Rare,
    icon: '✦',
    chargeRounds: 3,
    skillCardId: 'skill-belial',
    description: 'Raises damage for the rest of combat.',
  },
  'book-shadows': {
    id: 'book-shadows',
    isaacId: 58,
    name: 'Book of Shadows',
    kind: ItemKind.Active,
    pool: [RewardPool.Treasure, RewardPool.Angel, RewardPool.Library],
    quality: RewardQuality.Rare,
    icon: '◈',
    chargeRounds: 3,
    skillCardId: 'skill-shadows',
    description: 'Wraps Isaac in 12 shield.',
  },
  'tammys-head': {
    id: 'tammys-head',
    isaacId: 38,
    name: "Tammy's Head",
    kind: ItemKind.Active,
    pool: [
      RewardPool.Treasure,
      RewardPool.Secret,
      RewardPool.SuperSecret,
      RewardPool.Library,
      RewardPool.Crawlspace,
    ],
    quality: RewardQuality.Uncommon,
    icon: '✺',
    chargeRounds: 3,
    skillCardId: 'skill-tammy',
    description: 'Fires attacks in every direction.',
  },
  'the-nail': {
    id: 'the-nail',
    isaacId: 83,
    name: 'The Nail',
    kind: ItemKind.Active,
    pool: [RewardPool.Devil, RewardPool.Curse, RewardPool.Sacrifice],
    quality: RewardQuality.Rare,
    icon: '†',
    chargeRounds: 6,
    skillCardId: 'skill-nail',
    description: 'Grants a black heart and room armor.',
  },
  'glowing-hourglass': {
    id: 'glowing-hourglass',
    isaacId: 422,
    name: 'Glowing Hour Glass',
    kind: ItemKind.Active,
    pool: [RewardPool.Shop, RewardPool.Planetarium, RewardPool.Dice, RewardPool.Vault],
    quality: RewardQuality.Rare,
    icon: '⌛',
    chargeRounds: 6,
    skillCardId: 'skill-hourglass',
    description: 'Makes every enemy miss its next action.',
  },
  'sad-onion': {
    id: 'sad-onion',
    name: 'The Sad Onion',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.RoomClear, RewardPool.Crawlspace],
    quality: RewardQuality.Uncommon,
    icon: '◌',
    description: '+0.25 fire rate. Every four attacks produces a free echo shot.',
    effects: [{ stat: 'fireRate', amount: 0.25 }],
    fusion: { damageMultiplier: 1.1, projectileScale: 1.25 },
  },
  'spoon-bender': {
    id: 'spoon-bender',
    name: 'Spoon Bender',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Challenge, RewardPool.Error],
    quality: RewardQuality.Rare,
    icon: '⌁',
    description: 'Homing attacks can bend toward enemies outside a straight firing line.',
    effects: [{ curvedShots: true }],
    fusion: { curvedShots: true, projectileScale: 1.1 },
  },
  'crickets-head': {
    id: 'crickets-head',
    name: "Cricket's Head",
    kind: ItemKind.Passive,
    pool: [
      RewardPool.Treasure,
      RewardPool.Elite,
      RewardPool.Challenge,
      RewardPool.Vault,
      RewardPool.Crawlspace,
    ],
    quality: RewardQuality.Legendary,
    icon: '♟',
    description: '×1.5 damage multiplier.',
    effects: [{ stat: 'damageMultiplier', multiplier: 1.5 }],
    fusion: { damageMultiplier: 1.5, projectileScale: 1.2 },
  },
  'magic-mushroom': {
    id: 'magic-mushroom',
    name: 'Magic Mushroom',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Vault, RewardPool.Crawlspace, RewardPool.Error],
    quality: RewardQuality.Legendary,
    icon: '♠',
    description: 'All stats up and one red-heart container.',
    effects: [
      { stat: 'damageMultiplier', multiplier: 1.25 },
      { stat: 'armor', amount: 1 },
      { stat: 'fireRate', amount: 0.15 },
      { redContainers: 1 },
    ],
    fusion: { damageMultiplier: 1.25, projectileScale: 1.55, knockback: 2 },
  },
  lunch: {
    id: 'lunch',
    isaacId: 22,
    name: 'Lunch',
    nameZh: '午餐',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Bedroom],
    quality: RewardQuality.Common,
    icon: '◒',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container and fill it.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 1 }],
  },
  dinner: {
    id: 'dinner',
    isaacId: 23,
    name: 'Dinner',
    nameZh: '正餐',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Bedroom],
    quality: RewardQuality.Common,
    icon: '◉',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container and fill it.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 1 }],
  },
  dessert: {
    id: 'dessert',
    isaacId: 24,
    name: 'Dessert',
    nameZh: '甜点',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Bedroom],
    quality: RewardQuality.Common,
    icon: '♨',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container and fill it.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 1 }],
  },
  breakfast: {
    id: 'breakfast',
    isaacId: 25,
    name: 'Breakfast',
    nameZh: '早餐',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Bedroom],
    quality: RewardQuality.Common,
    icon: '⌑',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container and fill it.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 1 }],
  },
  'rotten-meat': {
    id: 'rotten-meat',
    isaacId: 26,
    name: 'Rotten Meat',
    nameZh: '烂肉',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Curse],
    quality: RewardQuality.Common,
    icon: '✖',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container and fill it.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 1 }],
  },
  'raw-liver': {
    id: 'raw-liver',
    isaacId: 16,
    name: 'Raw Liver',
    nameZh: '生肝',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Secret, RewardPool.SuperSecret],
    quality: RewardQuality.Uncommon,
    icon: '♥',
    combatCard: false,
    description: 'Permanent pickup. Add two red-heart containers and fill them.',
    descriptionZh: '战斗外永久拾取：增加两颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 2 }],
  },
  'the-body': {
    id: 'the-body',
    isaacId: 334,
    name: 'The Body',
    nameZh: '肉体',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Angel, RewardPool.SuperSecret],
    quality: RewardQuality.Rare,
    icon: '♧',
    combatCard: false,
    description: 'Permanent pickup. Add three red-heart containers and fill them.',
    descriptionZh: '战斗外永久拾取：增加三颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 3 }],
  },
  'midnight-snack': {
    id: 'midnight-snack',
    isaacId: 456,
    name: 'Midnight Snack',
    nameZh: '夜宵',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Bedroom, RewardPool.Vault],
    quality: RewardQuality.Common,
    icon: '☾',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container and fill it.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限，并恢复新增的红心。',
    effects: [{ redContainers: 1 }],
  },
  stigmata: {
    id: 'stigmata',
    isaacId: 138,
    name: 'Stigmata',
    nameZh: '圣痕',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Angel],
    quality: RewardQuality.Uncommon,
    icon: '†',
    combatCard: false,
    description: 'Permanent pickup. Add one red-heart container, fill it, and gain +1 base damage.',
    descriptionZh: '战斗外永久拾取：增加一颗红心上限并恢复新增红心，基础攻击伤害 +1。',
    effects: [{ redContainers: 1 }, { stat: 'baseDamage', amount: 1 }],
  },
  'stem-cells': {
    id: 'stem-cells',
    isaacId: 176,
    name: 'Stem Cells',
    nameZh: '干细胞',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss],
    quality: RewardQuality.Common,
    icon: '❉',
    combatCard: false,
    description: 'Permanent pickup. Each heart holds 3 more HP and gains the new capacity.',
    descriptionZh: '战斗外永久拾取：每颗心的容量增加 3 点，并补充新增容量。',
    effects: [{ heartSize: HEART_SIZE_UPGRADE_AMOUNT }],
  },
  placenta: {
    id: 'placenta',
    isaacId: 218,
    name: 'Placenta',
    nameZh: '胎盘',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Bedroom],
    quality: RewardQuality.Uncommon,
    icon: '◉',
    combatCard: false,
    description: 'Permanent pickup. Each heart holds 3 more HP and gains the new capacity.',
    descriptionZh: '战斗外永久拾取：每颗心的容量增加 3 点，并补充新增容量。',
    effects: [{ heartSize: HEART_SIZE_UPGRADE_AMOUNT }],
  },
  'old-bandage': {
    id: 'old-bandage',
    isaacId: 219,
    name: 'Old Bandage',
    nameZh: '旧绷带',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Curse],
    quality: RewardQuality.Uncommon,
    icon: '▧',
    combatCard: false,
    description: 'Permanent pickup. Each heart holds 3 more HP and gains the new capacity.',
    descriptionZh: '战斗外永久拾取：每颗心的容量增加 3 点，并补充新增容量。',
    effects: [{ heartSize: HEART_SIZE_UPGRADE_AMOUNT }],
  },
  'blood-bag': {
    id: 'blood-bag',
    isaacId: 119,
    name: 'Blood Bag',
    nameZh: '血袋',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Arcade, RewardPool.Vault],
    quality: RewardQuality.Uncommon,
    icon: '▰',
    combatCard: false,
    description: 'Permanent pickup. Each heart holds 3 more HP and gains the new capacity.',
    descriptionZh: '战斗外永久拾取：每颗心的容量增加 3 点，并补充新增容量。',
    effects: [{ heartSize: HEART_SIZE_UPGRADE_AMOUNT }],
  },
  'bucket-of-lard': {
    id: 'bucket-of-lard',
    isaacId: 129,
    name: 'Bucket of Lard',
    nameZh: '桶装猪油',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.SuperSecret],
    quality: RewardQuality.Common,
    icon: '▣',
    combatCard: false,
    description: 'Permanent pickup. Each heart holds 3 more HP and gains the new capacity.',
    descriptionZh: '战斗外永久拾取：每颗心的容量增加 3 点，并补充新增容量。',
    effects: [{ heartSize: HEART_SIZE_UPGRADE_AMOUNT }],
  },
  marrow: {
    id: 'marrow',
    isaacId: 541,
    name: 'Marrow',
    nameZh: '骨髓',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Boss, RewardPool.Secret, RewardPool.SuperSecret],
    quality: RewardQuality.Uncommon,
    icon: '◇',
    combatCard: false,
    description: 'Permanent pickup. Each heart holds 3 more HP and gains the new capacity.',
    descriptionZh: '战斗外永久拾取：每颗心的容量增加 3 点，并补充新增容量。',
    effects: [{ heartSize: HEART_SIZE_UPGRADE_AMOUNT }],
  },
  squeezy: {
    id: 'squeezy',
    name: 'Squeezy',
    kind: ItemKind.Passive,
    pool: [RewardPool.Boss, RewardPool.RoomClear, RewardPool.Challenge, RewardPool.Bedroom],
    quality: RewardQuality.Rare,
    icon: '≋',
    description: '+0.2 fire rate and two soul hearts.',
    effects: [{ stat: 'fireRate', amount: 0.2 }, { soulHearts: 2 }],
    fusion: { damageMultiplier: 1.1, projectileScale: 1.3, slowTurns: 2 },
  },
  'holy-mantle': {
    id: 'holy-mantle',
    name: 'Holy Mantle',
    kind: ItemKind.Passive,
    pool: [RewardPool.Angel, RewardPool.Treasure, RewardPool.Sacrifice],
    quality: RewardQuality.Legendary,
    icon: '♢',
    description: '+15 starting shield in every room.',
    effects: [{ stat: 'baseShield', amount: 15 }],
    unlock: { event: UnlockEvent.FlawlessFloor, label: 'Clear a floor without red-heart damage' },
  },
  'steam-sale': {
    id: 'steam-sale',
    name: 'Steam Sale',
    kind: ItemKind.Passive,
    pool: [RewardPool.Shop, RewardPool.Arcade, RewardPool.Vault],
    quality: RewardQuality.Uncommon,
    icon: '%',
    combatCard: false,
    description: 'Shop prices are 50% lower.',
    effects: [{ stat: 'shopDiscount', amount: 0.5 }],
    unlock: { event: UnlockEvent.Wealthy, label: 'Hold at least 15 coins' },
  },
  compass: {
    id: 'compass',
    name: 'The Compass',
    kind: ItemKind.Passive,
    pool: [RewardPool.Shop, RewardPool.Secret, RewardPool.Crawlspace],
    quality: RewardQuality.Uncommon,
    icon: '⌖',
    combatCard: false,
    description: 'Reveals every normal room on the floor.',
    effects: [{ revealAll: true }],
  },
  'blue-map': {
    id: 'blue-map',
    name: 'Blue Map',
    kind: ItemKind.Passive,
    pool: [RewardPool.Shop, RewardPool.Secret, RewardPool.SuperSecret],
    quality: RewardQuality.Uncommon,
    icon: '▦',
    combatCard: false,
    description: 'Reveals secret and super-secret rooms.',
    effects: [{ revealSecrets: true }],
    unlock: { event: UnlockEvent.SecretHunter, label: 'Open both secret rooms on one floor' },
  },
  'wooden-spoon': {
    id: 'wooden-spoon',
    name: 'Wooden Spoon',
    kind: ItemKind.Passive,
    pool: [RewardPool.LargeRoom, RewardPool.Bedroom, RewardPool.Crawlspace],
    quality: RewardQuality.Common,
    icon: '♧',
    combatCard: false,
    description: 'Permanently adds 1 movement range. This item never enters the combat deck.',
    effects: [{ stat: 'movementSpeed', amount: 1 }],
  },
  'moms-heels': {
    id: 'moms-heels',
    name: "Mom's Heels",
    kind: ItemKind.Passive,
    pool: [RewardPool.LargeRoom, RewardPool.Curse, RewardPool.Crawlspace],
    quality: RewardQuality.Common,
    icon: '⌁',
    combatCard: false,
    description: 'Permanently adds 1 attack range. This item never enters the combat deck.',
    effects: [{ stat: 'attackRange', amount: 1 }],
  },
  'the-belt': {
    id: 'the-belt',
    name: 'The Belt',
    kind: ItemKind.Passive,
    pool: [RewardPool.LargeRoom, RewardPool.Shop, RewardPool.Challenge],
    quality: RewardQuality.Uncommon,
    icon: '▰',
    combatCard: false,
    description: 'Permanently adds 4 starting shield. This item never enters the combat deck.',
    effects: [{ stat: 'baseShield', amount: 4 }],
  },
  'wire-coat-hanger': {
    id: 'wire-coat-hanger',
    name: 'Wire Coat Hanger',
    kind: ItemKind.Passive,
    pool: [RewardPool.LargeRoom, RewardPool.Challenge, RewardPool.Vault],
    quality: RewardQuality.Uncommon,
    icon: '⌁',
    combatCard: false,
    description: 'Permanently adds 1 base attack damage. This item never enters the combat deck.',
    effects: [{ stat: 'baseDamage', amount: 1 }],
  },
  'torn-photo': {
    id: 'torn-photo',
    name: 'Torn Photo',
    kind: ItemKind.Passive,
    pool: [RewardPool.LargeRoom, RewardPool.Shop, RewardPool.Arcade],
    quality: RewardQuality.Uncommon,
    icon: '▱',
    combatCard: false,
    description: 'Permanently adds 0.15 fire rate. This item never enters the combat deck.',
    effects: [{ stat: 'fireRate', amount: 0.15 }],
  },
  'small-rock': {
    id: 'small-rock',
    name: 'Small Rock',
    kind: ItemKind.Passive,
    pool: [RewardPool.LargeRoom, RewardPool.Secret, RewardPool.Crawlspace, RewardPool.Vault],
    quality: RewardQuality.Rare,
    icon: '◆',
    combatCard: false,
    description: 'Permanently adds 2 base attack damage and 1 armor, but removes 1 movement range.',
    effects: [
      { stat: 'baseDamage', amount: 2 },
      { stat: 'armor', amount: 1 },
      { stat: 'movementSpeed', amount: -1 },
    ],
  },
  pentagram: {
    id: 'pentagram',
    name: 'Pentagram',
    kind: ItemKind.Passive,
    pool: [RewardPool.Devil, RewardPool.Elite, RewardPool.Curse, RewardPool.Sacrifice],
    quality: RewardQuality.Rare,
    icon: '☆',
    description: '×1.2 damage and +10% Devil chance.',
    effects: [{ stat: 'damageMultiplier', multiplier: 1.2 }],
    fusion: { damageMultiplier: 1.2, poisonTurns: 2, poisonDamage: 3 },
  },
  'goat-head': {
    id: 'goat-head',
    name: 'Goat Head',
    kind: ItemKind.Passive,
    pool: [RewardPool.Devil, RewardPool.Curse, RewardPool.SuperSecret],
    quality: RewardQuality.Rare,
    icon: '♈',
    combatCard: false,
    description: 'A Devil or Angel room is guaranteed after each boss.',
    effects: [{ guaranteeDeal: true }],
  },
  wafer: {
    id: 'wafer',
    name: 'The Wafer',
    kind: ItemKind.Passive,
    pool: [RewardPool.Angel, RewardPool.Sacrifice, RewardPool.Bedroom],
    quality: RewardQuality.Legendary,
    icon: '⊙',
    description: 'Enemy hits cannot exceed 15 damage before armor.',
    effects: [{ damageCap: 15 }],
  },
  'sacred-heart': {
    id: 'sacred-heart',
    name: 'Sacred Heart',
    kind: ItemKind.Passive,
    pool: [RewardPool.Angel, RewardPool.Sacrifice, RewardPool.SuperSecret, RewardPool.Error],
    quality: RewardQuality.Legendary,
    icon: '♡',
    description: '×1.6 damage and +15% critical chance.',
    effects: [
      { stat: 'damageMultiplier', multiplier: 1.6 },
      { stat: 'critChance', amount: 0.15 },
    ],
    fusion: { damageMultiplier: 1.6, projectileScale: 1.4, curvedShots: true },
    unlock: { event: UnlockEvent.AngelLoyalty, label: 'Skip two Devil rooms in one run' },
  },
  brimstone: {
    id: 'brimstone',
    name: 'Brimstone',
    kind: ItemKind.Passive,
    pool: [RewardPool.Devil, RewardPool.Curse, RewardPool.Error],
    quality: RewardQuality.Legendary,
    icon: '♨',
    description: 'Basic attacks become a beam that hits every enemy for 85% damage.',
    effects: [{ attackMode: AttackMode.Brimstone }],
    fusion: { attackMode: AttackMode.Brimstone, damageMultiplier: 1.2, projectileScale: 1.3 },
    unlock: { event: UnlockEvent.MomClear, label: "Defeat Mom's Leg" },
  },
  'moms-knife': {
    id: 'moms-knife',
    name: "Mom's Knife",
    kind: ItemKind.Passive,
    pool: [RewardPool.Devil, RewardPool.Treasure, RewardPool.Challenge, RewardPool.Error],
    quality: RewardQuality.Legendary,
    icon: '◢',
    description: 'Basic attacks become piercing knife strikes with ×1.6 power.',
    effects: [{ attackMode: AttackMode.Knife }],
    fusion: { attackMode: AttackMode.Knife, damageMultiplier: 1.35, knockback: 1 },
    unlock: { event: UnlockEvent.MomClear, label: "Defeat Mom's Leg" },
  },
  'tech-x': {
    id: 'tech-x',
    name: 'Tech X',
    kind: ItemKind.Passive,
    pool: [RewardPool.Treasure, RewardPool.Planetarium, RewardPool.Dice, RewardPool.Error],
    quality: RewardQuality.Legendary,
    icon: '◎',
    description: 'Ring shots hit all enemies and erase 3 shield.',
    effects: [{ attackMode: AttackMode.TechX }],
    fusion: { attackMode: AttackMode.TechX, projectileScale: 1.65, slowTurns: 1 },
    unlock: { event: UnlockEvent.ElitePerfect, label: 'Beat an elite without taking damage' },
  },
  terra: {
    id: 'terra',
    name: 'Terra',
    kind: ItemKind.Passive,
    pool: [RewardPool.Planetarium, RewardPool.Secret, RewardPool.Crawlspace],
    quality: RewardQuality.Rare,
    icon: '●',
    description: '+3 base damage and +1 armor.',
    effects: [
      { stat: 'baseDamage', amount: 3 },
      { stat: 'armor', amount: 1 },
    ],
    fusion: { flatDamage: 3, projectileScale: 1.35, knockback: 2 },
  },
  luna: {
    id: 'luna',
    name: 'Luna',
    kind: ItemKind.Passive,
    pool: [RewardPool.Planetarium, RewardPool.Secret, RewardPool.SuperSecret],
    quality: RewardQuality.Rare,
    icon: '☾',
    description: '+1 draw and reveals secret rooms.',
    effects: [{ stat: 'drawCount', amount: 1 }, { revealSecrets: true }],
  },
};

/**
 * The generated catalog supplies every Repentance/Repentance+ collectible.
 * Curated and project-specific definitions override generic adaptations by
 * stable ID and by Isaac collectible ID. The second key prevents aliases such
 * as `the-book-of-belial` and `book-belial` from becoming two runtime items.
 */
const CUSTOM_ISAAC_IDS = new Set(
  Object.values(CUSTOM_ITEM_DEFINITIONS)
    .map((item) => item.isaacId)
    .filter((id): id is number => id !== undefined),
);
const AUTHORED_ISAAC_IDS = new Set([
  ...CUSTOM_ISAAC_IDS,
  ...Object.values(CURATED_ITEMS)
    .map((item) => item.isaacId)
    .filter((id): id is number => id !== undefined),
]);

export const ITEMS: Record<string, ItemDefinition> = {
  ...Object.fromEntries(
    Object.entries(FULL_ISAAC_ITEMS).filter(
      ([id, item]) =>
        !(id in CUSTOM_ITEM_DEFINITIONS) &&
        !(id in CURATED_ITEMS) &&
        (item.isaacId === undefined || !AUTHORED_ISAAC_IDS.has(item.isaacId)),
    ),
  ),
  ...Object.fromEntries(
    Object.entries(CURATED_ITEMS).filter(
      ([id, item]) =>
        !(id in CUSTOM_ITEM_DEFINITIONS) &&
        (item.isaacId === undefined || !CUSTOM_ISAAC_IDS.has(item.isaacId)),
    ),
  ),
  ...CUSTOM_ITEM_DEFINITIONS,
};

for (const item of Object.values(ITEMS)) {
  if (isFamiliarItem(item)) {
    item.combatCard = false;
    item.timing = ItemUseTiming.Permanent;
    item.fusion = undefined;
    item.description =
      'Permanent familiar. Deploys around Isaac and automatically attacks each player round.';
    item.descriptionZh = '永久宝宝：部署在以撒周围，每个玩家回合自动攻击。';
  }
  if (item.kind === ItemKind.Active) item.timing ??= ItemUseTiming.ActiveCharge;
  if (item.kind === ItemKind.Passive && item.combatCard === false) item.timing ??= ItemUseTiming.Permanent;
  if (item.kind === ItemKind.Passive && item.combatCard !== false) item.timing ??= ItemUseTiming.CombatCard;
}

const PASSIVE_CARD_TEXT: Record<string, string> = {
  'sad-onion': 'Gain +0.25 fire rate for this combat.',
  'spoon-bender': 'Attacks can target enemies diagonally for this combat.',
  'crickets-head': 'Multiply damage by 1.5 for this combat.',
  'magic-mushroom': 'Gain ×1.25 damage, +1 armor, +0.15 fire rate, and recover 15 HP this combat.',
  breakfast: 'Permanent pickup: add one red-heart container and fill it.',
  squeezy: 'Gain +0.2 fire rate and 20 shield this combat.',
  'holy-mantle': 'Gain 15 shield.',
  'steam-sale': 'Gain 2 coins.',
  compass: 'Reveal every normal room on this floor.',
  'blue-map': 'Reveal the Secret and Super Secret rooms on this floor.',
  pentagram: 'Multiply damage by 1.2 for this combat.',
  'goat-head': 'Guarantee the Devil or Angel door after this floor boss.',
  wafer: 'Cap incoming hits at 15 damage for this combat.',
  'sacred-heart': 'Gain ×1.6 damage and +15% critical chance for this combat.',
  brimstone: 'Change attacks to Brimstone for this combat.',
  'moms-knife': "Change attacks to Mom's Knife for this combat.",
  'tech-x': 'Change attacks to Tech X for this combat.',
  terra: 'Gain +3 damage and +1 armor for this combat.',
  luna: 'Draw one card and reveal both secret rooms.',
};

export function passiveCardId(itemId: string): string {
  return `item:${itemId}`;
}

export function itemUsesCombatCard(item: ItemDefinition): boolean {
  return (
    item.kind === ItemKind.Passive && item.combatCard !== false && item.timing !== ItemUseTiming.Permanent
  );
}

function itemCardTarget(item: ItemDefinition): CardTarget {
  const effects = [
    ...(item.cardEffects ?? []),
    ...(item.actions?.flatMap((action) => action.effects ?? []) ?? []),
  ];
  if (effects.some((effect) => effect.target === CardTarget.Enemy)) return CardTarget.Enemy;
  if (effects.some((effect) => effect.target === CardTarget.AllEnemies)) return CardTarget.AllEnemies;
  return CardTarget.Self;
}

for (const item of Object.values(ITEMS).filter((entry) => entry.kind === ItemKind.Passive)) {
  const id = passiveCardId(item.id);
  CARDS[id] = {
    id,
    name: item.name,
    type: CardType.Item,
    cost: item.cardCost ?? Math.max(1, item.quality - 1),
    target: itemCardTarget(item),
    itemId: item.id,
    icon: item.icon,
    quality: item.quality,
    rewardPools: [...item.pool],
    description: PASSIVE_CARD_TEXT[item.id] ?? item.description,
    effects: item.cardEffects,
  };
}

for (const item of Object.values(ITEMS).filter(
  (entry) => entry.kind === ItemKind.Active && Boolean(entry.skillCardId),
)) {
  const id = item.skillCardId!;
  if (CARDS[id]) continue;
  CARDS[id] = {
    id,
    name: item.name,
    type: CardType.Skill,
    cost: item.cardCost ?? Math.max(0, Math.min(3, 1 + Math.floor(item.quality / 2))),
    target: itemCardTarget(item),
    itemId: item.id,
    icon: item.icon,
    quality: item.quality,
    rewardPools: [...item.pool],
    description: item.description,
    effects: item.cardEffects,
  };
}

export const ITEM_UNLOCK_PROGRESSION = buildItemUnlockProgression(ITEMS, ACHIEVEMENT_DEFINITIONS);

export const DEFAULT_UNLOCKS = [...ITEM_UNLOCK_PROGRESSION.initialItemIds];

export function achievementItemUnlocks(achievementId: AchievementId): readonly string[] {
  return ITEM_UNLOCK_PROGRESSION.achievementItemIds[achievementId] ?? [];
}

export function completedAchievementItemUnlocks(achievementIds: readonly AchievementId[]): readonly string[] {
  return [...new Set(achievementIds.flatMap((achievementId) => achievementItemUnlocks(achievementId)))];
}

export const DEFAULT_PROFILE: ProfileState = {
  itemUnlockProgressionVersion: CURRENT_ITEM_UNLOCK_PROGRESSION_VERSION,
  wins: 0,
  losses: 0,
  bestScore: 0,
  unlockedItemIds: DEFAULT_UNLOCKS,
  discoveredItemIds: ['d6'],
  eventFlags: [],
  achievementProgress: {
    completedIds: [],
    completedAt: {},
    lifetimeCounters: {},
    platformSyncedIds: {},
  },
};

export const ENEMIES: Record<string, EnemyDefinition> = {
  fly: {
    id: 'fly',
    name: 'Attack Fly',
    maxHp: 18,
    attack: 9,
    armor: 0,
    movementSpeed: 3,
    attackRange: 1,
    visionRange: 6,
    footprintWidth: 1,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '✣',
  },
  pooter: {
    id: 'pooter',
    name: 'Pooter',
    maxHp: 24,
    attack: 12,
    armor: 0,
    movementSpeed: 2,
    attackRange: 5,
    visionRange: 8,
    footprintWidth: 1,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '◉',
  },
  spider: {
    id: 'spider',
    name: 'Big Spider',
    maxHp: 30,
    attack: 14,
    armor: 1,
    movementSpeed: 3,
    attackRange: 1,
    visionRange: 5,
    footprintWidth: 2,
    footprintHeight: 2,
    movementPattern: EnemyMovementPattern.DiagonalJump,
    icon: '✳',
  },
  horf: {
    id: 'horf',
    name: 'Horf',
    maxHp: 34,
    attack: 16,
    armor: 1,
    movementSpeed: 2,
    attackRange: 5,
    visionRange: 8,
    footprintWidth: 1,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '●',
  },
  charger: {
    id: 'charger',
    name: 'Charger',
    maxHp: 38,
    attack: 18,
    armor: 1,
    movementSpeed: 4,
    attackRange: 1,
    visionRange: 7,
    footprintWidth: 2,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '➤',
  },
  globin: {
    id: 'globin',
    name: 'Globin',
    maxHp: 44,
    attack: 17,
    armor: 2,
    movementSpeed: 2,
    attackRange: 2,
    visionRange: 6,
    footprintWidth: 1,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '♟',
  },
  knight: {
    id: 'knight',
    name: 'Knight',
    maxHp: 52,
    attack: 21,
    armor: 4,
    movementSpeed: 2,
    attackRange: 1,
    visionRange: 6,
    footprintWidth: 2,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '♞',
  },
  vis: {
    id: 'vis',
    name: 'Vis',
    maxHp: 46,
    attack: 23,
    armor: 2,
    movementSpeed: 1,
    attackRange: 6,
    visionRange: 9,
    footprintWidth: 2,
    footprintHeight: 1,
    movementPattern: EnemyMovementPattern.Cardinal,
    icon: '☢',
  },
  leaper: {
    id: 'leaper',
    name: 'Leaper',
    maxHp: 56,
    attack: 22,
    armor: 3,
    movementSpeed: 4,
    attackRange: 1,
    visionRange: 6,
    footprintWidth: 2,
    footprintHeight: 2,
    movementPattern: EnemyMovementPattern.DiagonalJump,
    icon: '♣',
  },
  'fat-bat': {
    id: 'fat-bat',
    name: 'Fat Bat',
    maxHp: 88,
    attack: 23,
    armor: 3,
    movementSpeed: 3,
    attackRange: 2,
    visionRange: 7,
    footprintWidth: 2,
    footprintHeight: 2,
    movementPattern: EnemyMovementPattern.DiagonalJump,
    elite: true,
    icon: '◆',
  },
  'champion-knight': {
    id: 'champion-knight',
    name: 'Champion Knight',
    maxHp: 110,
    attack: 27,
    armor: 5,
    movementSpeed: 3,
    attackRange: 1,
    visionRange: 7,
    footprintWidth: 2,
    footprintHeight: 2,
    movementPattern: EnemyMovementPattern.Cardinal,
    elite: true,
    icon: '♛',
  },
  monstro: {
    id: 'monstro',
    name: 'Monstro',
    maxHp: 120,
    attack: 22,
    armor: 2,
    movementSpeed: 2,
    attackRange: 3,
    visionRange: 8,
    footprintWidth: 4,
    footprintHeight: 4,
    movementPattern: EnemyMovementPattern.DiagonalJump,
    boss: true,
    icon: '◉',
  },
  duke: {
    id: 'duke',
    name: 'Duke of Flies',
    maxHp: 155,
    attack: 25,
    armor: 2,
    movementSpeed: 2,
    attackRange: 4,
    visionRange: 9,
    footprintWidth: 4,
    footprintHeight: 4,
    movementPattern: EnemyMovementPattern.Cardinal,
    boss: true,
    icon: '♚',
  },
  gurdy: {
    id: 'gurdy',
    name: 'Gurdy',
    maxHp: 190,
    attack: 28,
    armor: 3,
    movementSpeed: 1,
    attackRange: 6,
    visionRange: 10,
    footprintWidth: 4,
    footprintHeight: 4,
    movementPattern: EnemyMovementPattern.Cardinal,
    boss: true,
    icon: '☉',
  },
  fatty: {
    id: 'fatty',
    name: 'Mega Fatty',
    maxHp: 225,
    attack: 31,
    armor: 4,
    movementSpeed: 2,
    attackRange: 2,
    visionRange: 8,
    footprintWidth: 4,
    footprintHeight: 4,
    movementPattern: EnemyMovementPattern.DiagonalJump,
    boss: true,
    icon: '⬤',
  },
  cage: {
    id: 'cage',
    name: 'The Cage',
    maxHp: 270,
    attack: 35,
    armor: 5,
    movementSpeed: 3,
    attackRange: 3,
    visionRange: 9,
    footprintWidth: 4,
    footprintHeight: 4,
    movementPattern: EnemyMovementPattern.DiagonalJump,
    boss: true,
    icon: '▣',
  },
  mom: {
    id: 'mom',
    name: "Mom's Leg",
    maxHp: 360,
    attack: 40,
    armor: 6,
    movementSpeed: 2,
    attackRange: 5,
    visionRange: 11,
    footprintWidth: 5,
    footprintHeight: 5,
    movementPattern: EnemyMovementPattern.Cardinal,
    boss: true,
    icon: '♠',
  },
};

const FLOOR_POOLS = [
  ['fly', 'pooter', 'spider'],
  ['fly', 'pooter', 'spider'],
  ['horf', 'charger', 'globin'],
  ['horf', 'charger', 'globin'],
  ['knight', 'vis', 'leaper'],
  ['knight', 'vis', 'leaper'],
] as const;

const BOSSES = ['monstro', 'duke', 'gurdy', 'fatty', 'cage', 'mom'] as const;

export function getEnemy(id: string): EnemyDefinition {
  const enemy = ENEMIES[id];
  if (!enemy) throw new Error(`Unknown enemy: ${id}`);
  return enemy;
}

export function enemyPoolForFloor(floorIndex: number): EnemyDefinition[] {
  return (FLOOR_POOLS[floorIndex] ?? FLOOR_POOLS[5]).map(getEnemy);
}

export function eliteForFloor(floorIndex: number): EnemyDefinition {
  return getEnemy(floorIndex >= 4 ? 'champion-knight' : 'fat-bat');
}

export function bossForFloor(floorIndex: number): EnemyDefinition {
  return getEnemy(BOSSES[floorIndex] ?? 'mom');
}
