import type { AchievementDefinition, AchievementRequirement } from '../domain/achievement.js';
import {
  AchievementCategory,
  AchievementComparison,
  AchievementId,
  AchievementMetric,
  AchievementScope,
  AchievementTier,
  RewardQuality,
} from '../domain/enums.js';

const lifetime = (metric: AchievementMetric, target: number): AchievementRequirement => ({
  metric,
  scope: AchievementScope.Lifetime,
  comparison: AchievementComparison.AtLeast,
  target,
});

const runAtLeast = (metric: AchievementMetric, target: number): AchievementRequirement => ({
  metric,
  scope: AchievementScope.Run,
  comparison: AchievementComparison.AtLeast,
  target,
});

const runAtMost = (metric: AchievementMetric, target: number): AchievementRequirement => ({
  metric,
  scope: AchievementScope.Run,
  comparison: AchievementComparison.AtMost,
  target,
});

function achievement(
  definition: Omit<AchievementDefinition, 'steamKey'> & { steamKey?: string },
): AchievementDefinition {
  return {
    ...definition,
    steamKey: definition.steamKey ?? `ACH_${definition.id.replaceAll('-', '_').toUpperCase()}`,
  };
}

export const ACHIEVEMENT_DEFINITIONS: readonly AchievementDefinition[] = [
  achievement({
    id: AchievementId.BasementAwakening,
    name: 'Something Stirs Below',
    nameZh: '地底有什么在蠕动',
    description: 'Defeat your first boss.',
    descriptionZh: '首次击败任意首领。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Bronze,
    icon: '◉',
    requirements: [lifetime(AchievementMetric.BossesDefeated, 1)],
    rewardItemIds: ['monstros-tooth', 'little-chubby'],
  }),
  achievement({
    id: AchievementId.MomLeg,
    name: 'A Taste of Her Own Medicine',
    nameZh: '让妈妈尝尝自己的手段',
    description: "Defeat Mom's Leg.",
    descriptionZh: '击败妈妈的腿。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Silver,
    icon: '♠',
    requirements: [lifetime(AchievementMetric.MomLegKills, 1)],
    rewardItemIds: ['brimstone', 'moms-knife'],
  }),
  achievement({
    id: AchievementId.MomLegVeteran,
    name: 'The Harbingers Are Loose',
    nameZh: '天启骑士挣脱了束缚',
    description: "Defeat Mom's Leg three times.",
    descriptionZh: '累计击败妈妈的腿3次。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Gold,
    icon: 'Ⅲ',
    requirements: [lifetime(AchievementMetric.MomLegKills, 3)],
    rewardItemIds: ['cube-of-meat', 'book-of-revelations'],
  }),
  achievement({
    id: AchievementId.MomHeart,
    name: 'The Womb',
    nameZh: '子宫深处',
    description: "Defeat Mom's Heart.",
    descriptionZh: '击败妈妈的心脏。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Gold,
    hidden: true,
    icon: '♥',
    requirements: [lifetime(AchievementMetric.MomHeartKills, 1)],
    rewardItemIds: ['rubber-cement', 'ipecac'],
  }),
  achievement({
    id: AchievementId.ItLives,
    name: 'It Lives!',
    nameZh: '它还活着！',
    description: 'Defeat It Lives!',
    descriptionZh: '击败“它还活着！”。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Gold,
    hidden: true,
    icon: '☣',
    requirements: [lifetime(AchievementMetric.ItLivesKills, 1)],
    rewardItemIds: ['the-halo', 'godhead'],
  }),
  achievement({
    id: AchievementId.Isaac,
    name: 'The Cathedral',
    nameZh: '大教堂',
    description: 'Defeat Isaac.',
    descriptionZh: '击败以撒。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Platinum,
    hidden: true,
    icon: '△',
    requirements: [lifetime(AchievementMetric.IsaacKills, 1)],
    rewardItemIds: ['d20', 'the-mind'],
  }),
  achievement({
    id: AchievementId.Satan,
    name: 'Sheol',
    nameZh: '阴间',
    description: 'Defeat Satan.',
    descriptionZh: '击败撒但。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Platinum,
    hidden: true,
    icon: '▼',
    requirements: [lifetime(AchievementMetric.SatanKills, 1)],
    rewardItemIds: ['the-nail', 'judas-shadow'],
  }),
  achievement({
    id: AchievementId.BlueBaby,
    name: '???',
    nameZh: '？？？',
    description: 'Defeat ???.',
    descriptionZh: '击败？？？。',
    category: AchievementCategory.Progression,
    tier: AchievementTier.Platinum,
    hidden: true,
    icon: '?',
    requirements: [lifetime(AchievementMetric.BlueBabyKills, 1)],
    rewardItemIds: ['death-certificate', 'r-key'],
  }),
  achievement({
    id: AchievementId.BossHunter,
    name: 'Boss Hunter',
    nameZh: '首领猎人',
    description: 'Defeat 10 bosses.',
    descriptionZh: '累计击败10个首领。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Silver,
    icon: '♚',
    requirements: [lifetime(AchievementMetric.BossesDefeated, 10)],
    rewardItemIds: ['book-belial', 'tammys-head'],
  }),
  achievement({
    id: AchievementId.BossSlayer,
    name: 'Boss Slayer',
    nameZh: '首领终结者',
    description: 'Defeat 50 bosses.',
    descriptionZh: '累计击败50个首领。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Platinum,
    icon: '♛',
    requirements: [lifetime(AchievementMetric.BossesDefeated, 50)],
    rewardItemIds: ['mega-blast', 'plan-c'],
  }),
  achievement({
    id: AchievementId.EliteHunter,
    name: 'Champion Hunter',
    nameZh: '精英猎手',
    description: 'Defeat 10 elite enemies.',
    descriptionZh: '累计击败10个精英敌人。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Silver,
    icon: '◆',
    requirements: [lifetime(AchievementMetric.ElitesKilled, 10)],
    rewardItemIds: ['champion-belt', 'crown-of-light'],
  }),
  achievement({
    id: AchievementId.ElitePerfect,
    name: 'Untouchable Champion',
    nameZh: '无伤精英战',
    description: 'Defeat an elite without taking heart damage in its room.',
    descriptionZh: '在一场精英战中不受生命伤害并获胜。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Gold,
    icon: '◇',
    requirements: [lifetime(AchievementMetric.PerfectElites, 1)],
    rewardItemIds: ['tech-x'],
  }),
  achievement({
    id: AchievementId.FlawlessFloor,
    name: 'Basement Boy',
    nameZh: '地下室男孩',
    description: 'Clear a floor without taking red-heart damage.',
    descriptionZh: '在一整层中不受到红心伤害。',
    category: AchievementCategory.Challenge,
    tier: AchievementTier.Gold,
    icon: '□',
    requirements: [lifetime(AchievementMetric.FlawlessFloors, 1)],
    rewardItemIds: ['holy-mantle', 'wafer'],
  }),
  achievement({
    id: AchievementId.SacrificeNovice,
    name: 'A Small Offering',
    nameZh: '小小献礼',
    description: 'Sacrifice 30 red-heart HP in total.',
    descriptionZh: '在献祭房累计献出30点红心生命。',
    category: AchievementCategory.Sacrifice,
    tier: AchievementTier.Bronze,
    icon: '†',
    requirements: [lifetime(AchievementMetric.SacrificeHp, 30)],
    rewardItemIds: ['razor-blade'],
  }),
  achievement({
    id: AchievementId.SacrificeDevotee,
    name: 'Devotion',
    nameZh: '虔信',
    description: 'Sacrifice 90 red-heart HP in total.',
    descriptionZh: '在献祭房累计献出90点红心生命。',
    category: AchievementCategory.Sacrifice,
    tier: AchievementTier.Silver,
    icon: '‡',
    requirements: [lifetime(AchievementMetric.SacrificeHp, 90)],
    rewardItemIds: ['sacrificial-altar'],
  }),
  achievement({
    id: AchievementId.SacrificeMartyr,
    name: 'Sword Above the Head',
    nameZh: '悬于头顶之剑',
    description: 'Sacrifice 180 red-heart HP in total.',
    descriptionZh: '在献祭房累计献出180点红心生命。',
    category: AchievementCategory.Sacrifice,
    tier: AchievementTier.Platinum,
    icon: '♱',
    requirements: [lifetime(AchievementMetric.SacrificeHp, 180)],
    rewardItemIds: ['damocles'],
  }),
  achievement({
    id: AchievementId.ShopRegular,
    name: 'Window Shopper',
    nameZh: '商店常客',
    description: 'Spend 50 coins in shops.',
    descriptionZh: '在商店累计消费50枚硬币。',
    category: AchievementCategory.Economy,
    tier: AchievementTier.Bronze,
    icon: '¢',
    requirements: [lifetime(AchievementMetric.CoinsSpent, 50)],
    rewardItemIds: ['coupon'],
  }),
  achievement({
    id: AchievementId.ShopPatron,
    name: 'Store Upgrade',
    nameZh: '商店升级',
    description: 'Spend 200 coins in shops.',
    descriptionZh: '在商店累计消费200枚硬币。',
    category: AchievementCategory.Economy,
    tier: AchievementTier.Silver,
    icon: '%',
    requirements: [lifetime(AchievementMetric.CoinsSpent, 200)],
    rewardItemIds: ['steam-sale', 'restock'],
  }),
  achievement({
    id: AchievementId.ShopTycoon,
    name: 'Member for Life',
    nameZh: '终身会员',
    description: 'Spend 500 coins in shops.',
    descriptionZh: '在商店累计消费500枚硬币。',
    category: AchievementCategory.Economy,
    tier: AchievementTier.Gold,
    icon: '¤',
    requirements: [lifetime(AchievementMetric.CoinsSpent, 500)],
    rewardItemIds: ['member-card', 'keepers-sack'],
  }),
  achievement({
    id: AchievementId.DeepPockets,
    name: 'Deep Pockets',
    nameZh: '腰缠万贯',
    description: 'Hold 55 coins at once.',
    descriptionZh: '同时持有55枚硬币。',
    category: AchievementCategory.Economy,
    tier: AchievementTier.Silver,
    icon: '$',
    requirements: [lifetime(AchievementMetric.MaxCoinsHeld, 55)],
    rewardItemIds: ['money-power', 'deep-pockets'],
  }),
  achievement({
    id: AchievementId.SecretSeeker,
    name: 'Something Is Hidden',
    nameZh: '墙后另有乾坤',
    description: 'Enter 10 Secret or Super Secret rooms.',
    descriptionZh: '累计进入10次隐藏房或超级隐藏房。',
    category: AchievementCategory.Exploration,
    tier: AchievementTier.Silver,
    icon: '⌖',
    requirements: [lifetime(AchievementMetric.SecretRoomsEntered, 10)],
    rewardItemIds: ['blue-map'],
  }),
  achievement({
    id: AchievementId.SecretMaster,
    name: 'Red Door Cartographer',
    nameZh: '红门绘图师',
    description: 'Enter 30 Secret or Super Secret rooms.',
    descriptionZh: '累计进入30次隐藏房或超级隐藏房。',
    category: AchievementCategory.Exploration,
    tier: AchievementTier.Gold,
    icon: '▦',
    requirements: [lifetime(AchievementMetric.SecretRoomsEntered, 30)],
    rewardItemIds: ['red-key'],
  }),
  achievement({
    id: AchievementId.Demolition,
    name: 'Demo Man',
    nameZh: '爆破专家',
    description: 'Use 25 bombs in combat or on the route map.',
    descriptionZh: '在战斗或路线中累计使用25枚炸弹。',
    category: AchievementCategory.Exploration,
    tier: AchievementTier.Silver,
    icon: '●',
    requirements: [lifetime(AchievementMetric.BombsUsed, 25)],
    rewardItemIds: ['mr-boom', 'mama-mega'],
  }),
  achievement({
    id: AchievementId.CardStudent,
    name: 'Deck Student',
    nameZh: '牌组学徒',
    description: 'Play 250 cards.',
    descriptionZh: '累计打出250张牌。',
    category: AchievementCategory.Deckbuilding,
    tier: AchievementTier.Bronze,
    icon: '▤',
    requirements: [lifetime(AchievementMetric.CardsPlayed, 250)],
    rewardItemIds: ['deck-of-cards', 'booster-pack'],
  }),
  achievement({
    id: AchievementId.CardMaster,
    name: 'Deck Master',
    nameZh: '牌组大师',
    description: 'Play 1,000 cards.',
    descriptionZh: '累计打出1000张牌。',
    category: AchievementCategory.Deckbuilding,
    tier: AchievementTier.Gold,
    icon: '▣',
    requirements: [lifetime(AchievementMetric.CardsPlayed, 1000)],
    rewardItemIds: ['blank-card'],
  }),
  achievement({
    id: AchievementId.MonsterHunter,
    name: 'Monster Hunter',
    nameZh: '怪物猎人',
    description: 'Defeat 100 enemies.',
    descriptionZh: '累计击败100个敌人。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Silver,
    icon: '×',
    requirements: [lifetime(AchievementMetric.EnemiesKilled, 100)],
    rewardItemIds: ['deaths-list'],
  }),
  achievement({
    id: AchievementId.MonsterSlayer,
    name: 'Monster Slayer',
    nameZh: '怪物终结者',
    description: 'Defeat 500 enemies.',
    descriptionZh: '累计击败500个敌人。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Gold,
    icon: '☠',
    requirements: [lifetime(AchievementMetric.EnemiesKilled, 500)],
    rewardItemIds: ['the-necronomicon'],
  }),
  achievement({
    id: AchievementId.AngelFaith,
    name: 'Angel Loyalty',
    nameZh: '天使的信赖',
    description: 'Reject two Devil doors in one run.',
    descriptionZh: '在一局游戏中拒绝2次恶魔房入口。',
    category: AchievementCategory.Challenge,
    tier: AchievementTier.Gold,
    icon: '△',
    requirements: [runAtLeast(AchievementMetric.AngelFavorGained, 2)],
    rewardItemIds: ['sacred-heart', 'the-soul'],
  }),
  achievement({
    id: AchievementId.DevilPact,
    name: 'The Pact',
    nameZh: '恶魔契约',
    description: 'Take three Devil deals across all runs.',
    descriptionZh: '累计接受3次恶魔交易。',
    category: AchievementCategory.Challenge,
    tier: AchievementTier.Silver,
    icon: '▼',
    requirements: [lifetime(AchievementMetric.DevilDealsTaken, 3)],
    rewardItemIds: ['goat-head', 'pentagram', 'sulfur'],
  }),
  achievement({
    id: AchievementId.Minimalist,
    name: 'Minimalist',
    nameZh: '极简主义',
    description: 'Win with 12 or fewer cards in the final deck.',
    descriptionZh: '以不超过12张牌的最终牌组获胜。',
    category: AchievementCategory.Deckbuilding,
    tier: AchievementTier.Gold,
    icon: '12',
    requirements: [runAtLeast(AchievementMetric.RunsWon, 1), runAtMost(AchievementMetric.FinalDeckSize, 12)],
    rewardItemIds: ['bag-of-crafting'],
  }),
  achievement({
    id: AchievementId.CommonSense,
    name: 'Common Sense',
    nameZh: '常识',
    description: 'Win without uncommon, rare, or legendary non-Skill cards in the final deck.',
    descriptionZh: '最终牌组中不含非普通品质的非主动牌并获胜。',
    category: AchievementCategory.Deckbuilding,
    tier: AchievementTier.Platinum,
    icon: '0',
    requirements: [
      runAtLeast(AchievementMetric.RunsWon, 1),
      runAtMost(AchievementMetric.FinalHighestCardQuality, RewardQuality.Common),
    ],
    rewardItemIds: ['rock-bottom'],
  }),
  achievement({
    id: AchievementId.SpeedClimber,
    name: 'Speed Climber',
    nameZh: '速通者',
    description: 'Win a run in 45 minutes or less.',
    descriptionZh: '在45分钟内完成一局游戏。',
    category: AchievementCategory.Challenge,
    tier: AchievementTier.Gold,
    icon: '»',
    requirements: [
      runAtLeast(AchievementMetric.RunsWon, 1),
      runAtMost(AchievementMetric.RunDurationSeconds, 45 * 60),
    ],
    rewardItemIds: ['stop-watch'],
  }),
  achievement({
    id: AchievementId.WhoNeedsItems,
    name: 'Who Needs Items?',
    nameZh: '谁需要道具？',
    description: 'Win while owning at most three passive items.',
    descriptionZh: '获胜时最多只拥有3件被动道具。',
    category: AchievementCategory.Challenge,
    tier: AchievementTier.Platinum,
    icon: '∅',
    requirements: [runAtLeast(AchievementMetric.RunsWon, 1), runAtMost(AchievementMetric.FinalItemCount, 3)],
    rewardItemIds: ['diplopia'],
  }),
  achievement({
    id: AchievementId.Impervious,
    name: 'Impervious',
    nameZh: '坚不可摧',
    description: 'Have 50 shield during combat.',
    descriptionZh: '在战斗中同时拥有50点护盾。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Silver,
    icon: '▰',
    requirements: [lifetime(AchievementMetric.MaxShield, 50)],
    rewardItemIds: ['book-shadows'],
  }),
  achievement({
    id: AchievementId.Adrenaline,
    name: 'Adrenaline',
    nameZh: '肾上腺素',
    description: 'Have 9 vitality during one turn.',
    descriptionZh: '在一个回合中同时拥有9点体力。',
    category: AchievementCategory.Combat,
    tier: AchievementTier.Gold,
    icon: '9',
    requirements: [lifetime(AchievementMetric.MaxVitality, 9)],
    rewardItemIds: ['9-volt', 'car-battery'],
  }),
  achievement({
    id: AchievementId.ComboMaster,
    name: 'Infinite Motion',
    nameZh: '永动连锁',
    description: 'Play eight cards in a single turn.',
    descriptionZh: '在同一个玩家回合打出8张牌。',
    category: AchievementCategory.Deckbuilding,
    tier: AchievementTier.Gold,
    icon: '∞',
    requirements: [lifetime(AchievementMetric.MaxCardsPlayedInTurn, 8)],
    rewardItemIds: ['echo-chamber', 'clear-rune'],
  }),
];

export const ACHIEVEMENTS: Readonly<Record<AchievementId, AchievementDefinition>> = Object.freeze(
  Object.fromEntries(ACHIEVEMENT_DEFINITIONS.map((entry) => [entry.id, entry])) as Record<
    AchievementId,
    AchievementDefinition
  >,
);

export const ACHIEVEMENT_REWARD_ITEM_IDS = new Set(
  ACHIEVEMENT_DEFINITIONS.flatMap((entry) => entry.rewardItemIds),
);
