import type { ItemDefinition } from '../domain/player.js';
import {
  CardEffectOpcode,
  CardTarget,
  ItemEffectFamily,
  ItemKind,
  ItemMechanic,
  ItemUseTiming,
  PocketItemAction,
  RewardPool,
  RewardQuality,
} from '../domain/enums.js';
import { ISAAC_ACTION_ITEM_DEFINITIONS } from './isaac-action-items.js';

export const CUSTOM_ITEM_DEFINITIONS: Record<string, ItemDefinition> = {
  ...ISAAC_ACTION_ITEM_DEFINITIONS,
  'travel-pack': {
    id: 'travel-pack',
    name: 'Travel Pack',
    nameZh: '旅行卡包',
    kind: ItemKind.Consumable,
    timing: ItemUseTiming.RunOnce,
    pocketAction: PocketItemAction.DeckEdit,
    family: ItemEffectFamily.Cycle,
    originalMechanics: [ItemMechanic.Deck],
    pool: [RewardPool.Shop, RewardPool.Vault, RewardPool.Crawlspace],
    quality: RewardQuality.Rare,
    icon: '▣',
    description:
      'Run-once pocket item. Rebuild the deck with up to 30 selected cards; empty slots are filled with Blank cards.',
    descriptionZh: '整局一次性携带道具。自由保留至多 30 张牌，不足 30 张的位置由空白牌填充。',
    combatCard: false,
  },
  diplopia: {
    id: 'diplopia',
    isaacId: 347,
    name: 'Diplopia',
    nameZh: '复视',
    kind: ItemKind.Consumable,
    timing: ItemUseTiming.RunOnce,
    pocketAction: PocketItemAction.DuplicateDeck,
    family: ItemEffectFamily.Draw,
    originalMechanics: [ItemMechanic.Deck, ItemMechanic.Reroll],
    pool: [RewardPool.Shop, RewardPool.Secret, RewardPool.Dice],
    quality: RewardQuality.Rare,
    icon: '◫',
    description: 'Run-once pocket item. Duplicate any selected cards in the current deck.',
    descriptionZh: '整局一次性携带道具。选择当前牌组中的任意牌，各复制一张加入牌组。',
    combatCard: false,
  },
  'r-key': {
    id: 'r-key',
    isaacId: 636,
    name: 'R Key',
    nameZh: 'R键',
    kind: ItemKind.Consumable,
    timing: ItemUseTiming.RunOnce,
    pocketAction: PocketItemAction.RestartRun,
    family: ItemEffectFamily.Wildcard,
    originalMechanics: [ItemMechanic.RoomControl, ItemMechanic.RiskReward],
    pool: [RewardPool.Secret, RewardPool.SuperSecret, RewardPool.Error],
    quality: RewardQuality.Legendary,
    icon: 'R',
    description: 'Run-once pocket item. Keep the deck, stats and inventory, then restart at Basement I.',
    descriptionZh: '整局一次性携带道具。保留牌组、属性与物品，从地下室一层重新开始。',
    combatCard: false,
  },
  'steam-sale': {
    id: 'steam-sale',
    isaacId: 64,
    name: 'Steam Sale',
    nameZh: 'Steam大促',
    kind: ItemKind.Consumable,
    timing: ItemUseTiming.RunOnce,
    pocketAction: PocketItemAction.ShopDiscount,
    family: ItemEffectFamily.Economy,
    originalMechanics: [ItemMechanic.Economy],
    pool: [RewardPool.Shop, RewardPool.Secret, RewardPool.Arcade],
    quality: RewardQuality.Uncommon,
    icon: '%',
    description: 'Run-once pocket item. All shop prices are reduced by 50% for the rest of the run.',
    descriptionZh: '整局一次性携带道具。使用后，本局剩余时间所有商店价格降低 50%。',
    combatCard: false,
  },
  'holy-protection': {
    id: 'holy-protection',
    name: 'Holy Protection',
    nameZh: '神圣庇护',
    kind: ItemKind.Consumable,
    timing: ItemUseTiming.FloorOnce,
    pocketAction: PocketItemAction.ClearDebuffs,
    family: ItemEffectFamily.Defense,
    originalMechanics: [ItemMechanic.Defense, ItemMechanic.Status],
    pool: [RewardPool.Angel],
    quality: RewardQuality.Rare,
    icon: '✞',
    description: 'Floor-once pocket item. Clear every current player debuff.',
    descriptionZh: '每层限用一次。清除玩家当前承受的全部负面状态。',
    combatCard: false,
  },
  damocles: {
    id: 'damocles',
    isaacId: 577,
    name: 'Damocles',
    nameZh: '达摩克利斯之剑',
    kind: ItemKind.Passive,
    timing: ItemUseTiming.CombatOnce,
    family: ItemEffectFamily.Wildcard,
    originalMechanics: [ItemMechanic.RiskReward, ItemMechanic.Attack],
    pool: [RewardPool.Sacrifice, RewardPool.Devil],
    quality: RewardQuality.Legendary,
    icon: '†',
    cardCost: 1,
    description:
      'Combat-once. Item effects are doubled until the sword falls. At each round end it has a 50% chance to remove one full heart.',
    descriptionZh: '每场战斗限用一次。剑落下前道具效果翻倍；每回合结束有 50% 概率损失一整颗心。',
    cardEffects: [{ opcode: CardEffectOpcode.Damocles, target: CardTarget.Self }],
  },
  ragnarok: {
    id: 'ragnarok',
    name: 'Ragnarok',
    nameZh: '诸神黄昏',
    kind: ItemKind.Passive,
    timing: ItemUseTiming.CombatOnce,
    family: ItemEffectFamily.Draw,
    originalMechanics: [ItemMechanic.Deck, ItemMechanic.RiskReward],
    pool: [RewardPool.Sacrifice, RewardPool.Curse],
    quality: RewardQuality.Legendary,
    icon: 'ᚱ',
    cardCost: 2,
    description:
      'Combat-once. Ignore the retain limit and draw five at each round start; lose HP equal to retained hand size each round.',
    descriptionZh:
      '每场战斗限用一次。无视回合末手牌上限；每回合开始抽 5 张牌，回合结束损失等同手牌数的生命。',
    cardEffects: [{ opcode: CardEffectOpcode.Ragnarok, target: CardTarget.Self }],
  },
  'strong-stimulant': {
    id: 'strong-stimulant',
    name: 'Strong Stimulant',
    nameZh: '强效兴奋剂',
    kind: ItemKind.Passive,
    timing: ItemUseTiming.CombatOnce,
    family: ItemEffectFamily.Wildcard,
    originalMechanics: [ItemMechanic.RiskReward, ItemMechanic.Movement],
    pool: [RewardPool.Sacrifice, RewardPool.Curse, RewardPool.Challenge],
    quality: RewardQuality.Rare,
    icon: '⚕',
    cardCost: 2,
    description: 'Combat-once. Vitality costs are ignored for five rounds; afterwards lose one max vitality.',
    descriptionZh: '每场战斗限用一次。五回合内无视体力上限与消耗，结束后永久失去 1 点体力上限。',
    cardEffects: [{ opcode: CardEffectOpcode.Stimulant, turns: 5, target: CardTarget.Self }],
  },
  transposition: {
    id: 'transposition',
    name: 'Transposition',
    nameZh: '置换',
    kind: ItemKind.Passive,
    timing: ItemUseTiming.CombatOnce,
    family: ItemEffectFamily.Reroll,
    originalMechanics: [ItemMechanic.Reroll, ItemMechanic.Deck],
    pool: [RewardPool.Treasure, RewardPool.Dice, RewardPool.Secret],
    quality: RewardQuality.Rare,
    icon: '⇄',
    cardCost: 1,
    description:
      'Combat-once. Select non-charged item cards in the draw pile and replace each with another item.',
    descriptionZh: '每场战斗限用一次。选择抽牌堆中的非充能道具牌，将它们置换为其他道具牌。',
    cardEffects: [{ opcode: CardEffectOpcode.Transposition, target: CardTarget.Self }],
  },
  'blank-book': {
    id: 'blank-book',
    name: 'Blank Book',
    nameZh: '无字天书',
    kind: ItemKind.Passive,
    timing: ItemUseTiming.CombatOnce,
    family: ItemEffectFamily.Draw,
    originalMechanics: [ItemMechanic.Deck, ItemMechanic.Wildcard],
    pool: [RewardPool.Library, RewardPool.Secret, RewardPool.Treasure],
    quality: RewardQuality.Rare,
    icon: '▱',
    cardCost: 1,
    description:
      'Combat-once. Blank cards in hand may imitate any card currently in the draw or discard pile.',
    descriptionZh: '每场战斗限用一次。本场战斗中，手牌里的空白牌可模仿抽牌堆或弃牌堆中的任意牌。',
    cardEffects: [{ opcode: CardEffectOpcode.BlankBook, target: CardTarget.Self }],
  },
  'regret-medicine': {
    id: 'regret-medicine',
    name: 'Regret Medicine',
    nameZh: '后悔药',
    kind: ItemKind.Passive,
    timing: ItemUseTiming.CombatOnce,
    family: ItemEffectFamily.Reroll,
    originalMechanics: [ItemMechanic.RoomControl, ItemMechanic.Reroll],
    pool: [RewardPool.Shop, RewardPool.Treasure, RewardPool.Bedroom],
    quality: RewardQuality.Rare,
    icon: '↶',
    cardCost: 0,
    description: 'Combat-once. Restart the current room from its initial deployment state.',
    descriptionZh: '每场战斗限用一次。把当前房间恢复到进入并部署前的初始状态。',
    cardEffects: [{ opcode: CardEffectOpcode.RestartRoom, target: CardTarget.Self }],
  },
};
